# Generated by Django 5.0 on 2024-01-02 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerChild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banner/')),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='sub_category',
        ),
        migrations.RemoveField(
            model_name='category',
            name='sub_category',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
