# Generated by Django 5.0 on 2024-01-10 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_book_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='muqovasi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='pager',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='printed_year',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
